### ISSUE TITLE
Failing C to F unit test

### ISSUE THREAD

**Issue by taqpol** [rmotr-curriculum/pyp-class-questions#20]
I can't figure out why this test keeps failing. I checked the math and the control flow, and I don't see any errors in them. It also fails with two different results on whatever version the site is running and my machine, which is running 3.5.

```
def convert_temperature(temp, to=None):
    def c_to_fahrenheit():
        return temp*1.8+32

    def f_to_celsius():
        return (temp-32)*(5/9)

    if to != 'celsius' or to != 'fahrenheit':
        return f_to_celsius()
    elif to == 'fahrenheit':
        return c_to_fahrenheit()
    elif to == 'celsius':
        return f_to_celsius()
```

**Comment by md5sam** [comment]
@taqpol The issue seems to be with your choice of "OR" in your if-conditional. Your if-condition will always evaluate to True and run - regardless of whether your "to" argument is set to 'None', 'Celsius' or 'Fahrenheit'. Consequently, your elif statements are never evaluated. 

You might want to take a look at that "OR" and change it to a different logical operator.

**Comment by taqpol** [comment]
Just simplified the logic that  you mentioned, and it worked like a charm. Appreciate the help, @md5sam .
